# Generated by Django 2.2.12 on 2020-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='left_side',
            field=models.BooleanField(default=False),
        ),
    ]
