# Generated by Django 2.2.12 on 2020-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event_left_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='left_side',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.CharField(default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
