# Generated by Django 2.2.12 on 2020-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200629_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month_to_display',
            field=models.CharField(default='', max_length=60),
        ),
    ]
